/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import CapaClases.Administrador;
import CapaClases.Alumno;
import CapaMetodos.Metodos;
import javax.swing.JOptionPane;

/**
 *
 * @author Serginho
 */
public class JAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form JBanco
     */
    public JAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombreB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLimpiarB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarB = new javax.swing.JButton();
        txtComunaB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtDireccionB = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnModificarB = new javax.swing.JButton();
        btnEliminarB = new javax.swing.JButton();
        btnRegistrarB = new javax.swing.JButton();
        txtCarreraB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEdadB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Vista Administrador");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre: ");

        btnLimpiarB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiarB.setText("Limpiar");
        btnLimpiarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Carrera:");

        btnBuscarB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarB.setText("Buscar");
        btnBuscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Comuna:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Rut:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Dirección:");

        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });

        btnModificarB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificarB.setText("Modificar");
        btnModificarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarBActionPerformed(evt);
            }
        });

        btnEliminarB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarB.setText("Eliminar");
        btnEliminarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBActionPerformed(evt);
            }
        });

        btnRegistrarB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarB.setText("Registrar");
        btnRegistrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarBActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Edad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistrarB)
                        .addGap(28, 28, 28)
                        .addComponent(btnModificarB)
                        .addGap(33, 33, 33)
                        .addComponent(btnEliminarB)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(182, 182, 182))))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtComunaB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDireccionB, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEdadB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(137, 137, 137)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCarreraB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarB)
                                .addGap(28, 28, 28)))
                        .addComponent(btnLimpiarB)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarB)
                    .addComponent(btnLimpiarB))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtComunaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCarreraB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEdadB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarB)
                    .addComponent(btnEliminarB)
                    .addComponent(btnModificarB))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarBActionPerformed

    private void btnBuscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBActionPerformed
 

    }//GEN-LAST:event_btnBuscarBActionPerformed

    private void btnModificarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarBActionPerformed
        // TODO add your handling code here:
        Administrador ban = new Administrador();
        Metodos met = new Metodos();
        
        ban.setCodigo(Integer.parseInt(this.txtRut.getText().trim()));
        ban.setNombre(this.txtNombreB.getText().trim());
        ban.setSucursal(this.txtCarreraB.getText().trim());
        ban.setDireccion(this.txtDireccionB.getText().trim());
        ban.setComuna(this.txtComunaB.getText().trim());    
        
        met.modificarBanco(ban);
    }//GEN-LAST:event_btnModificarBActionPerformed

    private void btnEliminarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBActionPerformed
        // TODO add your handling code here:
        Metodos met = new Metodos();

        int opcion = 0;

        opcion = JOptionPane.showConfirmDialog(this, "¿Desea Eliminar?", "Eliminar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

        if(opcion == JOptionPane.YES_OPTION)
        {
            met.eliminarBanco(Integer.parseInt(this.txtRut.getText().trim()));
            this.limpiarCampos();
        }

    }//GEN-LAST:event_btnEliminarBActionPerformed

    private void btnRegistrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarBActionPerformed
        // TODO add your handling code here:
        if(this.txtRut.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this,"Ingrese el codigo ","Error",JOptionPane.ERROR_MESSAGE);
            this.txtRut.requestFocus();
            return;
        }

        if(this.txtNombreB.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this,"Ingrese su nombre ","Error",JOptionPane.ERROR_MESSAGE);
            this.txtNombreB.requestFocus();
            return;
        }

        if(this.txtDireccionB.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this,"Ingrese la direccion ","Error",JOptionPane.ERROR_MESSAGE);
            this.txtDireccionB.requestFocus();
            return;
        }

        if(this.txtComunaB.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this,"Ingrese el nombre de la comuna ","Error",JOptionPane.ERROR_MESSAGE);
            this.txtComunaB.requestFocus();
            return;
        }

        if(this.txtCarreraB.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this,"Ingrese el nombre de la sucursal ","Error",JOptionPane.ERROR_MESSAGE);
            this.txtCarreraB.requestFocus();
            return;
        }


        if(this.existeBanco() == true){
            JOptionPane.showMessageDialog(this, "Este codigo ya existe", "Error de Ingreso", JOptionPane.ERROR_MESSAGE);
        }
        else{
            insertarDatos();
            limpiarCampos();
        }
    }//GEN-LAST:event_btnRegistrarBActionPerformed

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(c<'0' || c>'9') evt.consume();{
        }
    }//GEN-LAST:event_txtRutKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarB;
    private javax.swing.JButton btnEliminarB;
    private javax.swing.JButton btnLimpiarB;
    private javax.swing.JButton btnModificarB;
    private javax.swing.JButton btnRegistrarB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtCarreraB;
    private javax.swing.JTextField txtComunaB;
    private javax.swing.JTextField txtDireccionB;
    private javax.swing.JTextField txtEdadB;
    private javax.swing.JTextField txtNombreB;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables

    private void insertarDatos() {
        
        Administrador ban = new Administrador();
        Metodos met = new Metodos();
        
        ban.setCodigo(Integer.parseInt(this.txtRut.getText().trim()));
        ban.setNombre(this.txtNombreB.getText().trim());
        ban.setSucursal(this.txtCarreraB.getText().trim());
        ban.setDireccion(this.txtDireccionB.getText().trim());
        ban.setComuna(this.txtComunaB.getText().trim());
               
        met.ingresarBanco(ban);
               
    }
    
    private void limpiarCampos(){
        txtRut.setText("");
        txtNombreB.setText("");
        txtCarreraB.setText("");
        txtDireccionB.setText("");
        txtComunaB.setText(""); 
    }
    
    private boolean existeBanco() {
        boolean siExiste = false;
        
        Metodos met = new Metodos();
        Administrador bn = met.buscarBanco(Integer.parseInt(this.txtRut.getText().trim()));
        if(this.txtRut.getText().trim().equals(bn.getCodigo())){
            siExiste = true;
        }
        else{
            siExiste = false;
        }
        return siExiste;
    }


}
